
package com.example.hangman;

import java.util.Random;

import androidx.appcompat.app.AppCompatActivity;

import android.annotation.SuppressLint;
import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.view.animation.Animation;
import android.view.animation.AnimationUtils;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.TextView;

import java.util.ArrayList;

public class GamePage extends AppCompatActivity {

    Button b1, b2, b3, b4, b5, b6, b7, b8, b9, b10, b11, b12, b13, b14, b15, b16, b17, b18, b19, b20, b21, b22, b23, b24, b25, b26;
    TextView space;
    ImageView hangman, gameOver, youWin, backGround;
    ArrayList<String> movies = new ArrayList<>();
    ArrayList<String> songs = new ArrayList<>();
    ArrayList<String> hollySongs = new ArrayList<>();
    ArrayList<String> kollySongs = new ArrayList<>();
    ArrayList<String> cricketPlayers = new ArrayList<>();
    ArrayList<String> hollyMovies = new ArrayList<>();
    ArrayList<String> kollyMovies = new ArrayList<>();
    ArrayList<String> stars = new ArrayList<>();
    ArrayList<String> hollyStars = new ArrayList<>();
    ArrayList<String> kollyStars = new ArrayList<>();
    String currentWord, enteredCharacter;
    StringBuffer blanks;
    int currentIndex, totalAttempts = 0, noOfSpaces = 0, num = 0,id;
    Animation anim;

    @SuppressLint("MissingInflatedId")
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_game_page);

        b1 = findViewById(R.id.b1);
        b2 = findViewById(R.id.b2);
        b3 = findViewById(R.id.b3);
        b4 = findViewById(R.id.b4);
        b5 = findViewById(R.id.b5);
        b6 = findViewById(R.id.b6);
        b7 = findViewById(R.id.b7);
        b8 = findViewById(R.id.b8);
        b9 = findViewById(R.id.b9);
        b10 = findViewById(R.id.b10);
        b11 = findViewById(R.id.b11);
        b12 = findViewById(R.id.b12);
        b13 = findViewById(R.id.b13);
        b14 = findViewById(R.id.b14);
        b15 = findViewById(R.id.b15);
        b16 = findViewById(R.id.b16);
        b17 = findViewById(R.id.b17);
        b18 = findViewById(R.id.b18);
        b19 = findViewById(R.id.b19);
        b20 = findViewById(R.id.b20);
        b21 = findViewById(R.id.b21);
        b22 = findViewById(R.id.b22);
        b23 = findViewById(R.id.b23);
        b24 = findViewById(R.id.b24);
        b25 = findViewById(R.id.b25);
        b26 = findViewById(R.id.b26);
        space = findViewById(R.id.space);
        hangman = findViewById(R.id.hangman);
        gameOver = findViewById(R.id.gameOver);
        youWin = findViewById(R.id.gameOver);
        backGround = findViewById(R.id.background);
        initialize();
    }

    public void initialize() {
        movies.add("SHIDDAT");
        movies.add("JAWAN");
        movies.add("PREMALU");
        movies.add("MANJUMMEL BOYS");
        movies.add("DANGAL");
        movies.add("PK");
        movies.add("RAB NE BANA DI JODI");
        movies.add("KOI MIL GAYA");
        movies.add("SITA RAMAM");
        movies.add("DUNKI");
        movies.add("JOE");

        movies.add("SHOLAY");
        movies.add("DILWALE DULHANIA LE JAYENGE");
        movies.add("LAGAAN");
        movies.add("ZINDAGI NA MILEGI DOBARA");
        movies.add("CHAK DE INDIA");
        movies.add("ANDHADHUN");
        movies.add("TAARE ZAMEEN PAR");
        movies.add("GULLY BOY");
        movies.add("KABIR SINGH");
        movies.add("QUEEN");
        movies.add("PATHAAN");
        movies.add("BHOLA");
        movies.add("ROCKY AUR RANI KI PREM KAHANI");
        movies.add("JAWAN");
        movies.add("ADIPURUSH");
        movies.add("SHEHZADA");
        movies.add("MRS CHATTERJEE VS NORWAY");
        movies.add("SAMRAT PRITHVIRAJ");
        movies.add("BADHAAI DO");
        movies.add("BADHAAI HO");
        movies.add("CHUP REVENGE OF THE ARTIST");


        movies.add("GOOD NEWWZ");
        movies.add("SIMMBA");
        movies.add("CHHICHHORE");
        movies.add("DILWALE");
        movies.add("RAAZ REBOOT");
        movies.add("RAAZ");
        movies.add("DYBBUK");
        movies.add("KRIYA");
        movies.add("SANAM RE");
        movies.add("GREAT GRAND MASTI");

        movies.add("BRAHMASTRA");
        movies.add("GANGUBAI KATHIAWADI");
        movies.add("LAAL SINGH CHADDHA");
        movies.add("DRISHYAM 2");
        movies.add("VIKRAM VEDHA");
        movies.add("JUG JUGG JEEYO");
        movies.add("BHOOL BHULAIYAA 2");
        movies.add("SHERSHAAH");
        movies.add("ATRANGI RE");
        movies.add("RADHE SHYAM");

        movies.add("SOORYAVANSHI");
        movies.add("BELL BOTTOM");
        movies.add("SHERNI");
        movies.add("MIMI");
        movies.add("THE GIRL ON THE TRAIN");
        movies.add("ROOHI");
        movies.add("SARDAR UDHAM");
        movies.add("TOOFAN");
        movies.add("TADAP");

        movies.add("HERA PHERI");
        movies.add("PHIR HERA PHERI");
        movies.add("ANDAZ APNA APNA");
        movies.add("GOLMAAL");
        movies.add("DHAMAAL");
        movies.add("CHUP CHUP KE");
        movies.add("HI NANNA");
        movies.add("VED");
        movies.add("JERSEY");
        movies.add("WELCOME");
        movies.add("WELCOME BACK");
        movies.add("HUNGAMA");
        movies.add("MUNNA BHAI MBBS");

        movies.add("ALONE");
        movies.add("HORROR STORY");
        movies.add("HASEE TOH PHASEE");
        movies.add("KAPOOR AND SONS");
        movies.add("SUI DHAAGA");
        movies.add("JUDWAA");
        movies.add("MAIN TERA HERO");
        movies.add("ISHQ MURSHID");
        movies.add("ABCD");

        movies.add("BAAHUBALI");
        movies.add("URI");
        movies.add("WAR");
        movies.add("GOLMAAL");
        movies.add("PADMAAVAT");
        movies.add("KABIR SINGH");
        movies.add("BAJRANGI BHAIJAAN");
        movies.add("SANJU");

        movies.add("BHOOT");
        movies.add("BHOOTNATH");
        movies.add("RAGINI MMS");
        movies.add("PHOONK");
        movies.add("KAALU");
        movies.add("EK THI DAYAN");
        movies.add("BHOOT RETURNS");
        movies.add("RAAT");
        movies.add("PARI");


        hollyMovies.add("TENANT");
        hollyMovies.add("AVENGERS");
        hollyMovies.add("THOR");
        hollyMovies.add("THE GODFATHER");
        hollyMovies.add("THE SHAWSHANK REDEMPTION");
        hollyMovies.add("THE DARK KNIGHT");
        hollyMovies.add("SCHINDLER LIST");
        hollyMovies.add("PULP FICTION");
        hollyMovies.add("THE LORD OF THE RINGS");
        hollyMovies.add("FORREST GUMP");
        hollyMovies.add("FIGHT CLUB");
        hollyMovies.add("THE MATRIX");
        hollyMovies.add("GOODFELLAS");
        hollyMovies.add("STAR WARS");
        hollyMovies.add("SEVEN");
        hollyMovies.add("THE SILENCE OF THE LAMBS");
        hollyMovies.add("THE LORD OF THE RINGS: THE FELLOWSHIP OF THE RING");
        hollyMovies.add("THE USUAL SUSPECTS");
        hollyMovies.add("THE LION KING");
        hollyMovies.add("SAVING PRIVATE RYAN");
        hollyMovies.add("THE GREEN MILE");
        hollyMovies.add("GLADIATOR");
        hollyMovies.add("BACK TO THE FUTURE");
        hollyMovies.add("THE DEPARTED");
        hollyMovies.add("INTERSTELLAR");
        hollyMovies.add("THE PRESTIGE");
        hollyMovies.add("DIE HARD");
        hollyMovies.add("INCEPTION");
        hollyMovies.add("THE SHAWSHANK REDEMPTION");
        hollyMovies.add("THE MATRIX");
        hollyMovies.add("THE DARK KNIGHT RISES");
        hollyMovies.add("THE GODFATHER PART II");
        hollyMovies.add("THE LORD OF THE RINGS THE TWO TOWERS");
        hollyMovies.add("FIGHT CLUB");
        hollyMovies.add("FORREST GUMP");
        hollyMovies.add("INCEPTION");
        hollyMovies.add("STAR WARS");
        hollyMovies.add("THE DARK KNIGHT");
        hollyMovies.add("PULP FICTION");
        hollyMovies.add("THE GODFATHER PART II");
        hollyMovies.add("THE MATRIX");
        hollyMovies.add("THE SHINING");
        hollyMovies.add("FIGHT CLUB");
        hollyMovies.add("THE GODFATHER");
        hollyMovies.add("THE DARK KNIGHT RISES");
        hollyMovies.add("PULP FICTION");
        hollyMovies.add("SCHINDLER'S LIST");
        hollyMovies.add("THE GOOD, THE BAD AND THE UGLY");
        hollyMovies.add("FORREST GUMP");
        hollyMovies.add("THE MATRIX");
        hollyMovies.add("INTERSTELLAR");
        hollyMovies.add("HOSTEL");
        hollyMovies.add("INCEPTION");
        hollyMovies.add("KNOCK KNOCK");


        kollyMovies.add("Baahubali The Beginning");
        kollyMovies.add("Baahubali The Conclusion");
        kollyMovies.add("Kabali");
        kollyMovies.add("Enthiran");
        kollyMovies.add("Sivaji");
        kollyMovies.add("Mersal");
        kollyMovies.add("Viswasam");
        kollyMovies.add("Bigil");
        kollyMovies.add("Petta");
        kollyMovies.add("Darbar");
        kollyMovies.add("Master");
        kollyMovies.add("Kaithi");
        kollyMovies.add("Asuran");
        kollyMovies.add("Vikram");
        kollyMovies.add("Soorarai Pottru");
        kollyMovies.add("Vada Chennai");
        kollyMovies.add("Jai Bhim");
        kollyMovies.add("Sarpatta Parambarai");
        kollyMovies.add("Karnan");
        kollyMovies.add("Maari");
        kollyMovies.add("VIP");
        kollyMovies.add("Theri");
        kollyMovies.add("Thuppakki");
        kollyMovies.add("Mankatha");
        kollyMovies.add("Ayan");
        kollyMovies.add("Singam");
        kollyMovies.add("Singam II");
        kollyMovies.add("Singam III");
        kollyMovies.add("Vishwaroopam");
        kollyMovies.add("Vishwaroopam II");
        kollyMovies.add("Anniyan");
        kollyMovies.add("I");
        kollyMovies.add("Kaala");
        kollyMovies.add("Robo");
        kollyMovies.add("NGK");
        kollyMovies.add("Irumbu Thirai");
        kollyMovies.add("Papanasam");
        kollyMovies.add("Thani Oruvan");
        kollyMovies.add("O Kadhal Kanmani");
        kollyMovies.add("Kaththi");
        kollyMovies.add("Yennai Arindhaal");
        kollyMovies.add("Vedalam");
        kollyMovies.add("Maari 2");
        kollyMovies.add("Kodi");
        kollyMovies.add("Remo");
        kollyMovies.add("Theri");
        kollyMovies.add("Rajini Murugan");
        kollyMovies.add("Vanamagan");
        kollyMovies.add("Thaana Serndha Kootam");
        kollyMovies.add("Mersal");
        kollyMovies.add("Vikram Vedha");
        kollyMovies.add("Petta");
        kollyMovies.add("Darbar");
        kollyMovies.add("NGK");
        kollyMovies.add("Sarkar");
        kollyMovies.add("Kanchana 3");
        kollyMovies.add("Kaithi");
        kollyMovies.add("Asuran");
        kollyMovies.add("Soorarai Pottru");
        kollyMovies.add("Viswasam");
        kollyMovies.add("Bigil");
        kollyMovies.add("Master");
        kollyMovies.add("Darbar");
        kollyMovies.add("Mookuthi Amman");
        kollyMovies.add("Doctor");
        kollyMovies.add("Vikram");
        kollyMovies.add("Beast");
        kollyMovies.add("Ponniyin Selvan: Part I");
        kollyMovies.add("Ponniyin Selvan: Part II");
        kollyMovies.add("Vikram Vedha");
        kollyMovies.add("Varisu");
        kollyMovies.add("Thunivu");
        kollyMovies.add("Sita Ramam");
        kollyMovies.add("Natchathiram Nagargiradhu");
        kollyMovies.add("Kadaisi Vivasayi");
        kollyMovies.add("Love Today");
        kollyMovies.add("Vikram Vedha");
        kollyMovies.add("Sarkaru Vaari Paata");
        kollyMovies.add("Don");
        kollyMovies.add("Etharkkum Thunindhavan");
        kollyMovies.add("Hey Sinamika");
        kollyMovies.add("KGF: Chapter II");
        kollyMovies.add("RRR");
        kollyMovies.add("Beast");
        kollyMovies.add("Vikram");
        kollyMovies.add("Kaathuvaakula Rendu Kaadhal");
        kollyMovies.add("Maharshi");
        kollyMovies.add("Sarileru Neekevvaru");
        kollyMovies.add("Ala Vaikunthapurramuloo");
        kollyMovies.add("Bheeshma");
        kollyMovies.add("Uppena");


        songs.add("BALAM PICHKARI");
        songs.add("LUT GAYE");
        songs.add("BEWAFA TERA MASOOM CHEHRA");
        songs.add("HAWA HAWAAI");
        songs.add("HAWA HAWA");
        songs.add("BESHARAM BEWAFA");
        songs.add("DHOKE PYAR KE");
        songs.add("CHIKNI CHAMELI");
        songs.add("LOVE STEREO");
        songs.add("ZINDA BANDA");
        songs.add("PHIR CHALA");
        songs.add("KINNA SONA");
        songs.add("MERI JAAN");
        songs.add("RASHQ E QAMAR");
        songs.add("CHHOD DENGE");

        songs.add("TUM HI HO");
        songs.add("CHAIYYA CHAIYYA");
        songs.add("JAI HO");
        songs.add("TUJH MEIN RAB DIKHTA HAI");
        songs.add("KABIRA");
        songs.add("BADTAMEEZ DIL");
        songs.add("DIL DHADAKNE DO");
        songs.add("TUM MILE");
        songs.add("KAL HO NAA HO");
        songs.add("SURAJ HUA MADDHAM");

        songs.add("APNA TIME AAYEGA");
        songs.add("GHUNGROO");
        songs.add("BEKHAYALI");
        songs.add("TUM HI AANA");
        songs.add("SHAYAD");
        songs.add("MUKKALA MUQABLA");
        songs.add("GHOOMAR");
        songs.add("NASHE SI CHADH GAYI");
        songs.add("MALANG");
        songs.add("PEE LOON");

        songs.add("BESABRIYAAN");
        songs.add("RATAAN LAMBIYAN");
        songs.add("NAACHO NAACHO");
        songs.add("JUGNU");
        songs.add("TUM JO MILO");
        songs.add("DOOBEY");
        songs.add("SHAVA SHAVA");
        songs.add("NAIN TERE");
        songs.add("PARAM SUNDARI");

        songs.add("TERE VAASTE");
        songs.add("JHOOME JO PATHAAN");
        songs.add("BESHARAM RANG");
        songs.add("DOOBEY");
        songs.add("CHAKA CHAK");
        songs.add("PARAM SUNDARI");
        songs.add("DHOLIDA");
        songs.add("RATAAN LAMBIYAN");
        songs.add("NAACHO NAACHO");
        songs.add("JUGNU");
        songs.add("LAHORE");
        songs.add("RADHA");
        songs.add("MALANG");
        songs.add("AANKH MAREY");
        songs.add("GHOOMAR");
        songs.add("SHAYAD");
        songs.add("SHAVA SHAVA");
        songs.add("NAIN TERE");
        songs.add("NASHE SI CHADH GAYI");

        songs.add("TERA BAN JAUNGA");
        songs.add("BEKHAYALI");
        songs.add("TUM JO AAYE");
        songs.add("JEENE LAGA HOON");
        songs.add("PEHLA NASHA");
        songs.add("HUMKO HUMISE CHURA LO");
        songs.add("KABIRA");
        songs.add("AGAR TUM SAATH HO");
        songs.add("TUM MILE");
        songs.add("ZARA SA");
        songs.add("SUN SATHIYA");
        songs.add("JANAM JANAM");
        songs.add("TUJH MEIN RAB DIKHTA HAI");
        songs.add("GERUA");
        songs.add("HAWAYEIN");
        songs.add("RAABTA");
        songs.add("ENNA SONA");
        songs.add("TERA HONE LAGA HOON");
        songs.add("DIL DIYAN GALLAN");

        songs.add("MUNNI BADNAAM HUI");
        songs.add("SHEILA KI JAWANI");
        songs.add("FEVICOL SE");
        songs.add("BABY DOLL");
        songs.add("HAIKO NAACH");
        songs.add("OOH LA LA");
        songs.add("MASHALLAH");
        songs.add("PINKY");
        songs.add("ANARKALI DISCO CHALI");
        songs.add("KAJRA RE");
        songs.add("CHAMMAK CHALLO");
        songs.add("LAILA MAIN LAILA");
        songs.add("BIDI JALAILE");
        songs.add("ANARKALI");
        songs.add("HOTTIE WAAH");
        songs.add("KAMLI");
        songs.add("GHOOMAR");
        songs.add("DILBAR");
        songs.add("HUSN PARCHAM");
        songs.add("O SAKI SAKI");

        hollySongs.add("Bohemian Rhapsody");
        hollySongs.add("Imagine");
        hollySongs.add("Hey Jude");
        hollySongs.add("Like a Rolling Stone");
        hollySongs.add("I Cant Get No Satisfaction");
        hollySongs.add("Good Vibrations");
        hollySongs.add("Smells Like Teen Spirit");
        hollySongs.add("What a Wonderful World");
        hollySongs.add("Hotel California");
        hollySongs.add("Stairway to Heaven");
        hollySongs.add("Billie Jean");
        hollySongs.add("Born to Run");
        hollySongs.add("Purple Haze");
        hollySongs.add("Yesterday");
        hollySongs.add("Superstition");
        hollySongs.add("Take It Off");
        hollySongs.add("Sweet Child O Mine");
        hollySongs.add("Wonderwall");
        hollySongs.add("Beat It");
        hollySongs.add("Like a Prayer");
        hollySongs.add("Losing My Religion");
        hollySongs.add("Livin on a Prayer");
        hollySongs.add("Another Brick in the Wall");
        hollySongs.add("Crazy in Love");
        hollySongs.add("Rolling in the Deep");
        hollySongs.add("Umbrella");
        hollySongs.add("Poker Face");
        hollySongs.add("Hallelujah");
        hollySongs.add("Thriller");
        hollySongs.add("Dont Stop Believin");
        hollySongs.add("Let It Be");
        hollySongs.add("Every Breath You Take");
        hollySongs.add("Somebody to Love");
        hollySongs.add("Tiny Dancer");
        hollySongs.add("Shake It Off");
        hollySongs.add("Shape of You");
        hollySongs.add("Blinding Lights");
        hollySongs.add("Bad Guy");
        hollySongs.add("Uptown Funk");
        hollySongs.add("Old Town Road");
        hollySongs.add("Shallow");
        hollySongs.add("Roar");
        hollySongs.add("Dark Horse");
        hollySongs.add("Happy");
        hollySongs.add("Royals");
        hollySongs.add("Radioactive");
        hollySongs.add("Cant Feel My Face");
        hollySongs.add("Lean On");
        hollySongs.add("Thinking Out Loud");
        hollySongs.add("Sorry");
        hollySongs.add("Love Yourself");
        hollySongs.add("See You Again");
        hollySongs.add("One Dance");
        hollySongs.add("Closer");
        hollySongs.add("Rockstar");
        hollySongs.add("Sunflower");
        hollySongs.add("Senorita");
        hollySongs.add("Without Me");
        hollySongs.add("Sicko Mode");
        hollySongs.add("Lucid Dreams");
        hollySongs.add("Gods Plan");
        hollySongs.add("Humble");
        hollySongs.add("DNA");
        hollySongs.add("Despacito");
        hollySongs.add("Havana");
        hollySongs.add("In My Feelings");
        hollySongs.add("Girls Like You");
        hollySongs.add("Savage Love");
        hollySongs.add("Dynamite");
        hollySongs.add("Watermelon Sugar");
        hollySongs.add("Levitating");
        hollySongs.add("Peaches");
        hollySongs.add("Good For U");
        hollySongs.add("Stay");
        hollySongs.add("Butter");
        hollySongs.add("Mood");
        hollySongs.add("Montero");
        hollySongs.add("Save Your Tears");
        hollySongs.add("Positions");
        hollySongs.add("Blinding Lights");
        hollySongs.add("Bad Habits");
        hollySongs.add("Easy On Me");
        hollySongs.add("Kiss Me More");
        hollySongs.add("Heat Waves");
        hollySongs.add("Industry Baby");
        hollySongs.add("Need to Know");
        hollySongs.add("Deja Vu");
        hollySongs.add("Traitor");
        hollySongs.add("Best Friend");
        hollySongs.add("Good Days");
        hollySongs.add("Drivers License");
        hollySongs.add("Therefore I Am");

        kollySongs.add("Antha Arabic Kadaloram");
        kollySongs.add("Anjali Anjali");
        kollySongs.add("Chinna Chinna Aasai");
        kollySongs.add("Ennavale Adi Ennavale");
        kollySongs.add("Nila Kaigirathu");
        kollySongs.add("Thamizha Thamizha");
        kollySongs.add("Thendrale Thendrale");
        kollySongs.add("Uyire Uyire");
        kollySongs.add("Kannalanae");
        kollySongs.add("Pudhu Vellai Mazhai");
        kollySongs.add("Kaadhal Rojave");
        kollySongs.add("Kadhal Sadugudu");
        kollySongs.add("Poovukkul");
        kollySongs.add("Mundhinam Parthene");
        kollySongs.add("Sakkarakatti");
        kollySongs.add("Sahana Saral");
        kollySongs.add("Munbe Vaa");
        kollySongs.add("New York Nagaram");
        kollySongs.add("Nenjukkul Peidhidum");
        kollySongs.add("Adiye Kolluthey");
        kollySongs.add("Aathichudi");
        kollySongs.add("Oru Naalil");
        kollySongs.add("Suttum Vizhi");
        kollySongs.add("Aagayam Theepiditha");
        kollySongs.add("July Maadham");
        kollySongs.add("Aaruyire");
        kollySongs.add("Enge Enadhu Kavithai");
        kollySongs.add("Unakkenna Venum Sollu");
        kollySongs.add("Yaro Yarodi");
        kollySongs.add("Pachai Nirame");
        kollySongs.add("Swasamae Swasamae");
        kollySongs.add("Thamizhan Ennum");
        kollySongs.add("Uyirum Neeye");
        kollySongs.add("Margazhi Poove");
        kollySongs.add("Oru Deivam Thantha Poove");
        kollySongs.add("Adiyae Kolluthey");
        kollySongs.add("Marudhani Marudhani");
        kollySongs.add("Minsara Poove");
        kollySongs.add("Anjali Anjali Pushpanjali");
        kollySongs.add("Narumugaiye");
        kollySongs.add("Sundari Kannal");
        kollySongs.add("Ennavale");
        kollySongs.add("Malargale Malargale");
        kollySongs.add("Uyire Uyire");
        kollySongs.add("Kannathil Muthamittal");
        kollySongs.add("Oru Ponnu Onnu");
        kollySongs.add("Aayiram Kangal");
        kollySongs.add("Munbe Vaa");
        kollySongs.add("Poovukkul");
        kollySongs.add("Mundhinam Parthene");
        kollySongs.add("Kadhal Sadugudu");
        kollySongs.add("Pudhu Vellai Mazhai");
        kollySongs.add("Chinna Chinna Aasai");
        kollySongs.add("Ennavale Adi Ennavale");
        kollySongs.add("Nila Kaigirathu");
        kollySongs.add("Thamizha Thamizha");
        kollySongs.add("Thendrale Thendrale");
        kollySongs.add("Uyire Uyire");
        kollySongs.add("Kannalanae");
        kollySongs.add("Poovukkul");
        kollySongs.add("Pachai Nirame");
        kollySongs.add("Swasamae Swasamae");
        kollySongs.add("Thamizhan Ennum");
        kollySongs.add("Uyirum Neeye");
        kollySongs.add("Margazhi Poove");
        kollySongs.add("Oru Deivam Thantha Poove");
        kollySongs.add("Adiyae Kolluthey");
        kollySongs.add("Marudhani Marudhani");
        kollySongs.add("Minsara Poove");
        kollySongs.add("Anjali Anjali Pushpanjali");
        kollySongs.add("Narumugaiye");
        kollySongs.add("Sundari Kannal");
        kollySongs.add("Ennavale");
        kollySongs.add("Malargale Malargale");
        kollySongs.add("Kannathil Muthamittal");
        kollySongs.add("Oru Ponnu Onnu");
        kollySongs.add("Aayiram Kangal");
        kollySongs.add("Enge Enadhu Kavithai");
        kollySongs.add("Nenjukkul Peidhidum");
        kollySongs.add("Aathichudi");
        kollySongs.add("Sakkarakatti");
        kollySongs.add("New York Nagaram");

        stars.add("PULKIT SAMRAT");
        stars.add("NITANSHI GOEL");
        stars.add("KAREENA KAPOOR");
        stars.add("SAIF ALI KHAN");
        stars.add("SALMAN KHAN");
        stars.add("SHAHID KAPOOR");
        stars.add("AAMIR KHAN");

        stars.add("HEMA MALINI");
        stars.add("SONAKSHI SINHA");
        stars.add("TABU");
        stars.add("MANISHA KOIRALA");

        stars.add("SHAH RUKH KHAN");
        stars.add("RADHIKA MADAN");
        stars.add("KRITI SANON");
        stars.add("KIARA ADVANI");
        stars.add("RAJKUMAR RAO");
        stars.add("DISHA PATANI");
        stars.add("TIGER SHROFF");
        stars.add("ANANYA PANDEY");
        stars.add("AMY JACKSON");

        stars.add("AKSHAY KUMAR");
        stars.add("HRITHIK ROSHAN");
        stars.add("AMITABH BACHCHAN");
        stars.add("RANBIR KAPOOR");
        stars.add("RANVEER SINGH");
        stars.add("AJAY DEVGN");

        stars.add("JOHN ABRAHAM");
        stars.add("FARHAN AKHTAR");
        stars.add("ARJUN KAPOOR");
        stars.add("SUNNY DEOL");
        stars.add("SANJAY DUTT");
        stars.add("ANIL KAPOOR");
        stars.add("NASEERUDDIN SHAH");
        stars.add("IRRFAN KHAN");
        stars.add("SONAM KAPOOR");
        stars.add("PARINEETI CHOPRA");
        stars.add("JACQUELINE FERNANDEZ");
        stars.add("TAAPSEE PANNU");
        stars.add("SHRADDHA KAPOOR");
        stars.add("YAMI GAUTAM");
        stars.add("BHUMI PEDNEKAR");;
        stars.add("RISHI KAPOOR");
        stars.add("EMRAAN HASHMI");
        stars.add("ADITYA ROY KAPUR");
        stars.add("RITEISH DESHMUKH");
        stars.add("ABHISHEK BACHCHAN");
        stars.add("KARISHMA KAPOOR");
        stars.add("PREITY ZINTA");
        stars.add("KAJAL AGGARWAL");
        stars.add("FAWAD KHAN");
        stars.add("NARGIS FAKHRI");
        stars.add("ILEANA D'CRUZ");
        stars.add("ARJUN RAMPAL");
        stars.add("BOMAN IRANI");
        stars.add("NAWAZUDDIN SIDDIQUI");
        stars.add("ALI FAZAL");
        stars.add("PRIYANKA CHOPRA");
        stars.add("DEEPIKA PADUKONE");
        stars.add("KATRINA KAIF");
        stars.add("VARUN DHAWAN");
        stars.add("SIDDHARTH MALHOTRA");
        stars.add("TIGER SHROFF");
        stars.add("AYUSHMANN KHURRANA");
        stars.add("VICKY KAUSHAL");
        stars.add("KARTIK AARYAN");
        stars.add("SHUSHANT SINGH RAJPUT");
        stars.add("ALIA BHATT");
        stars.add("ANUSHKA SHARMA");
        stars.add("KANGANA RANAUT");
        stars.add("VIDYA BALAN");

        stars.add("JANHVI KAPOOR");
        stars.add("SARA ALI KHAN");
        stars.add("MADHURI DIXIT");
        stars.add("JUHI CHAWLA");
        stars.add("SUSHMITA SEN");
        stars.add("AISHWARYA RAI");
        stars.add("REKHA");
        stars.add("RANI MUKERJI");
        stars.add("KAJOL");
        stars.add("SHILPA SHETTY");

        hollyStars.add("Leonardo DiCaprio");
        hollyStars.add("Brad Pitt");
        hollyStars.add("Tom Hanks");
        hollyStars.add("Johnny Depp");
        hollyStars.add("Meryl Streep");
        hollyStars.add("Robert De Niro");
        hollyStars.add("Scarlett Johansson");
        hollyStars.add("Angelina Jolie");
        hollyStars.add("Will Smith");
        hollyStars.add("Julia Roberts");
        hollyStars.add("Morgan Freeman");
        hollyStars.add("Denzel Washington");
        hollyStars.add("Jennifer Lawrence");
        hollyStars.add("George Clooney");
        hollyStars.add("Matt Damon");
        hollyStars.add("Anne Hathaway");
        hollyStars.add("Christian Bale");
        hollyStars.add("Natalie Portman");
        hollyStars.add("Tom Cruise");
        hollyStars.add("Sandra Bullock");
        hollyStars.add("Robert Downey Jr.");
        hollyStars.add("Nicole Kidman");
        hollyStars.add("Charlize Theron");
        hollyStars.add("Hugh Jackman");
        hollyStars.add("Chris Hemsworth");
        hollyStars.add("Gal Gadot");
        hollyStars.add("Mark Ruffalo");
        hollyStars.add("Emma Stone");
        hollyStars.add("Ryan Gosling");
        hollyStars.add("Chris Evans");
        hollyStars.add("Anne Hathaway");
        hollyStars.add("Amy Adams");
        hollyStars.add("Harrison Ford");
        hollyStars.add("Cate Blanchett");
        hollyStars.add("Michael Fassbender");
        hollyStars.add("Chris Pratt");
        hollyStars.add("Jake Gyllenhaal");
        hollyStars.add("Samuel L. Jackson");
        hollyStars.add("Daniel Radcliffe");
        hollyStars.add("Emma Watson");
        hollyStars.add("Hugh Grant");
        hollyStars.add("Kate Winslet");
        hollyStars.add("Keira Knightley");
        hollyStars.add("Orlando Bloom");
        hollyStars.add("Bradley Cooper");
        hollyStars.add("Joaquin Phoenix");
        hollyStars.add("Tilda Swinton");
        hollyStars.add("Matthew McConaughey");
        hollyStars.add("James McAvoy");
        hollyStars.add("Margot Robbie");
        hollyStars.add("Keanu Reeves");
        hollyStars.add("Reese Witherspoon");
        hollyStars.add("Zoe Saldana");
        hollyStars.add("Ben Affleck");
        hollyStars.add("Alexandra Daddario");
        hollyStars.add("Viola Davis");
        hollyStars.add("Adam Driver");
        hollyStars.add("Lupita Nyong'o");
        hollyStars.add("Eddie Redmayne");
        hollyStars.add("Emily Blunt");
        hollyStars.add("Chris Pine");
        hollyStars.add("Sigourney Weaver");
        hollyStars.add("Timothée Chalamet");
        hollyStars.add("Zendaya");
        hollyStars.add("Idris Elba");
        hollyStars.add("Jessica Chastain");
        hollyStars.add("Will Ferrell");
        hollyStars.add("Sydney Sweeney");
        hollyStars.add("Saoirse Ronan");
        hollyStars.add("John Krasinski");
        hollyStars.add("Kirsten Dunst");
        hollyStars.add("Ryan Reynolds");
        hollyStars.add("Elizabeth Olsen");
        hollyStars.add("Blake Lively");
        hollyStars.add("Tom Hardy");
        hollyStars.add("Michelle Williams");
        hollyStars.add("Andy Serkis");
        hollyStars.add("Octavia Spencer");
        hollyStars.add("John Boyega");
        hollyStars.add("Oscar Isaac");
        hollyStars.add("Pedro Pascal");
        hollyStars.add("Rosamund Pike");
        hollyStars.add("Viggo Mortensen");
        hollyStars.add("Chadwick Boseman");
        hollyStars.add("Elizabeth Olsen");
        hollyStars.add("Paul Rudd");
        hollyStars.add("Benedict Cumberbatch");
        hollyStars.add("Channing Tatum");
        hollyStars.add("Mila Kunis");
        hollyStars.add("Jared Leto");
        hollyStars.add("Eva Green");
        hollyStars.add("Naomi Watts");
        hollyStars.add("Jason Momoa");
        hollyStars.add("Jason Statham");
        hollyStars.add("Helen Mirren");
        hollyStars.add("Judi Dench");
        hollyStars.add("Rami Malek");

        kollyStars.add("Rajinikanth");
        kollyStars.add("Kamal Haasan");
        kollyStars.add("Vijay");
        kollyStars.add("Ajith Kumar");
        kollyStars.add("Suriya");
        kollyStars.add("Vikram");
        kollyStars.add("Dhanush");
        kollyStars.add("Sivakarthikeyan");
        kollyStars.add("Vijay Sethupathi");
        kollyStars.add("Jayam Ravi");
        kollyStars.add("Karthi");
        kollyStars.add("Arya");
        kollyStars.add("Jiiva");
        kollyStars.add("Simbu");
        kollyStars.add("Madhavan");
        kollyStars.add("Prabhu");
        kollyStars.add("Sarath Kumar");
        kollyStars.add("Prakash Raj");
        kollyStars.add("Nassar");
        kollyStars.add("Arvind Swami");
        kollyStars.add("Chiyaan Vikram");
        kollyStars.add("Sathyaraj");
        kollyStars.add("Vivek");
        kollyStars.add("Vadivelu");
        kollyStars.add("Nayanthara");
        kollyStars.add("Trisha Krishnan");
        kollyStars.add("Anushka Shetty");
        kollyStars.add("Samantha Ruth Prabhu");
        kollyStars.add("Kajal Aggarwal");
        kollyStars.add("Tamannaah Bhatia");
        kollyStars.add("Hansika Motwani");
        kollyStars.add("Shruti Haasan");
        kollyStars.add("Keerthy Suresh");
        kollyStars.add("Rakul Preet Singh");
        kollyStars.add("Sai Pallavi");
        kollyStars.add("Amala Paul");
        kollyStars.add("Aishwarya Rajesh");
        kollyStars.add("Raashi Khanna");
        kollyStars.add("Nivetha Pethuraj");
        kollyStars.add("Regina Cassandra");
        kollyStars.add("Megha Akash");
        kollyStars.add("Priya Bhavani Shankar");
        kollyStars.add("Manjima Mohan");
        kollyStars.add("Madonna Sebastian");
        kollyStars.add("Aditi Rao Hydari");
        kollyStars.add("Andrea Jeremiah");
        kollyStars.add("Lakshmi Menon");
        kollyStars.add("Maadhavan");
        kollyStars.add("Anupama Parameswaran");
        kollyStars.add("Parvathy Thiruvothu");
        kollyStars.add("Jyothika");
        kollyStars.add("Simran");
        kollyStars.add("Shriya Saran");
        kollyStars.add("Sneha");
        kollyStars.add("Ritika Singh");
        kollyStars.add("Sivakami");
        kollyStars.add("Varalaxmi Sarathkumar");
        kollyStars.add("Nandita Swetha");
        kollyStars.add("Nazriya Nazim");
        kollyStars.add("Lavanya Tripathi");
        kollyStars.add("Sri Divya");
        kollyStars.add("Raai Laxmi");
        kollyStars.add("Santhosh Prathap");
        kollyStars.add("Shraddha Srinath");
        kollyStars.add("Ishwarya Menon");
        kollyStars.add("Athulya Ravi");
        kollyStars.add("Malavika Mohanan");
        kollyStars.add("Aparna Balamurali");
        kollyStars.add("Meera Jasmine");
        kollyStars.add("Mamta Mohandas");
        kollyStars.add("Ramya Krishnan");
        kollyStars.add("Khushbu Sundar");
        kollyStars.add("Bhumika Chawla");
        kollyStars.add("Tabu");
        kollyStars.add("Sangeetha Krish");
        kollyStars.add("R Parthiban");
        kollyStars.add("Goundamani");
        kollyStars.add("Senthil");
        kollyStars.add("Santhanam");
        kollyStars.add("Sathish");
        kollyStars.add("Soori");
        kollyStars.add("Premgi Amaren");
        kollyStars.add("Kishore");
        kollyStars.add("Samuthirakani");
        kollyStars.add("Nivin Pauly");
        kollyStars.add("Fahadh Faasil");
        kollyStars.add("Jai");
        kollyStars.add("Sasikumar");
        kollyStars.add("Vimal");
        kollyStars.add("Harish Kalyan");
        kollyStars.add("Kalaiyarasan");
        kollyStars.add("Robo Shankar");
        kollyStars.add("Yogi Babu");
        kollyStars.add("Karunakaran");
        kollyStars.add("Mime Gopi");
        kollyStars.add("Bobby Simha");
        kollyStars.add("Siddharth");
        kollyStars.add("Ashok Selvan");
        kollyStars.add("Anirudh Ravichander");
        kollyStars.add("Aadhi");
        kollyStars.add("Aari");
        kollyStars.add("Atharvaa");
        kollyStars.add("Sibiraj");
        kollyStars.add("Gautham Karthik");
        kollyStars.add("Natarajan Subramaniam");
        kollyStars.add("Sundeep Kishan");
        kollyStars.add("Vaibhav Reddy");
        kollyStars.add("Ashwin Kakumanu");
        kollyStars.add("Arun Vijay");
        kollyStars.add("Vikranth");
        kollyStars.add("Nakul");
        kollyStars.add("Ganesh Venkatraman");
        kollyStars.add("Naveen Chandra");
        kollyStars.add("Ramesh Thilak");
        kollyStars.add("Mohan Raja");
        kollyStars.add("Rajesh");
        kollyStars.add("Sundar C");
        kollyStars.add("K Bhagyaraj");
        kollyStars.add("RK Selvamani");
        kollyStars.add("Vignesh Shivan");
        kollyStars.add("Pa Ranjith");
        kollyStars.add("Atlee");
        kollyStars.add("Venkat Prabhu");
        kollyStars.add("M Rajesh");
        kollyStars.add("Karthik Subbaraj");
        kollyStars.add("Myskkin");
        kollyStars.add("Seenu Ramasamy");
        kollyStars.add("Lingusamy");
        kollyStars.add("S Shankar");
        kollyStars.add("Gautham Vasudev Menon");
        kollyStars.add("AR Murugadoss");
        kollyStars.add("Vetri Maaran");
        kollyStars.add("Balaji Sakthivel");
        kollyStars.add("Suseenthiran");
        kollyStars.add("SJ Surya");
        kollyStars.add("Selvaraghavan");
        kollyStars.add("Samuthirakani");
        kollyStars.add("Hari");
        kollyStars.add("CS Amudhan");
        kollyStars.add("Prabhu Deva");
        kollyStars.add("SP Jananathan");

        cricketPlayers.add("ARSHDEEP SINGH");
        cricketPlayers.add("JASPRIT BUMRAH");
        cricketPlayers.add("SANJU SAMSON");
        cricketPlayers.add("SOPHIE MOLINEUX");
        cricketPlayers.add("ROHIT SHARMA");
        cricketPlayers.add("SMRITI MANDANNA");
        cricketPlayers.add("ELLYSE PERRY");
        cricketPlayers.add("VIRAT KOHLI");
        cricketPlayers.add("AB DE VILLIERS");
        cricketPlayers.add("YUVRAJ SINGH");
        cricketPlayers.add("MS DHONI");
        cricketPlayers.add("HARLEEN DEOL");
        cricketPlayers.add("RAJAT PATIDAR");
        cricketPlayers.add("SHREYANKA PATIL");
        cricketPlayers.add("AMELIA KERR");
        cricketPlayers.add("MOHAMMAD SIRAJ");

        cricketPlayers.add("Mithali Raj");
        cricketPlayers.add("Ellyse Perry");
        cricketPlayers.add("Suzie Bates");
        cricketPlayers.add("Stafanie Taylor");
        cricketPlayers.add("Sunil Narine");
        cricketPlayers.add("Jofra Archer");
        cricketPlayers.add("Shikhar Dhawan");
        cricketPlayers.add("Hardik Pandya");
        cricketPlayers.add("Alyssa Healy");
        cricketPlayers.add("Tammy Beaumont");
        cricketPlayers.add("Sana Mir");
        cricketPlayers.add("Jemimah Rodrigue");
        cricketPlayers.add("Kuldeep Yadav");
        cricketPlayers.add("Mayank Agarwal");
        cricketPlayers.add("Ravindra Jadeja");
        cricketPlayers.add("Yuzvendra Chahal");
        cricketPlayers.add("Megan Schutt");
        cricketPlayers.add("Marizanne Kapp");
        cricketPlayers.add("Smriti Mandhana");
        cricketPlayers.add("Jhulan Goswami");
        cricketPlayers.add("Richa Ghosh");
        cricketPlayers.add("Arundhati Reddy");
        cricketPlayers.add("Priya Punia");
        cricketPlayers.add("Shafali Verma");
        cricketPlayers.add("Shaun Pollock");
        cricketPlayers.add("Nasser Hussain");
        cricketPlayers.add("Brian Lara");
        cricketPlayers.add("Courtney Walsh");
        cricketPlayers.add("Chaminda Vaas");
        cricketPlayers.add("Vivian Richards");
        cricketPlayers.add("Sunil Gavaskar");
        cricketPlayers.add("Kapil Dev");
        cricketPlayers.add("Anil Kumble");

        cricketPlayers.add("Rajeshwari Gayakwad");
        cricketPlayers.add("Shafali Verma");
        cricketPlayers.add("Marizanne Kapp");
        cricketPlayers.add("Sophie Devine");
        cricketPlayers.add("Chamari Athapaththu");
        cricketPlayers.add("Dane van Niekerk");
        cricketPlayers.add("Laura Wolvaardt");
        cricketPlayers.add("Amy Satterthwaite");
        cricketPlayers.add("Natalie Sciver");
        cricketPlayers.add("Deepti Sharma");
        cricketPlayers.add("Shikha Pandey");
        cricketPlayers.add("Nat Sciver");
        cricketPlayers.add("Pooja Vastrakar");
        cricketPlayers.add("Veda Krishnamurthy");
        cricketPlayers.add("Ekta Bisht");
        cricketPlayers.add("Radha Yadav");
        cricketPlayers.add("Taniya Bhatia");
        cricketPlayers.add("Heather Knight");
        cricketPlayers.add("Alyssa Healy");
        cricketPlayers.add("Sachin Tendulkar");
        cricketPlayers.add("Virat Kohli");
        cricketPlayers.add("Ricky Ponting");
        cricketPlayers.add("Jacques Kallis");
        cricketPlayers.add("AB de Villiers");
        cricketPlayers.add("Shane Warne");
        cricketPlayers.add("Glenn McGrath");
        cricketPlayers.add("Wasim Akram");
        cricketPlayers.add("Muttiah Muralitharan");
        cricketPlayers.add("Kumar Sangakkara");
        cricketPlayers.add("Mahela Jayawardene");
        cricketPlayers.add("Chris Gayle");
        cricketPlayers.add("Sourav Ganguly");
        cricketPlayers.add("Virender Sehwag");
        cricketPlayers.add("MS Dhoni");
        cricketPlayers.add("Rahul Dravid");
        cricketPlayers.add("Yuvraj Singh");
        cricketPlayers.add("Adam Gilchrist");
        cricketPlayers.add("Rohit Sharma");
        cricketPlayers.add("David Warner");
        cricketPlayers.add("Joe Root");
        cricketPlayers.add("Ben Stokes");
        cricketPlayers.add("Jasprit Bumrah");
        cricketPlayers.add("Kane Williamson");
        cricketPlayers.add("Babar Azam");
        cricketPlayers.add("Mitchell Starc");
        cricketPlayers.add("Rashid Khan");
        cricketPlayers.add("Quinton de Kock");
        cricketPlayers.add("Jason Holder");
        cricketPlayers.add("Kagiso Rabada");
        cricketPlayers.add("Ross Taylor");
        cricketPlayers.add("Pat Cummins");
        cricketPlayers.add("Faf du Plessis");
        cricketPlayers.add("Brendon McCullum");
        cricketPlayers.add("Imran Khan");
        cricketPlayers.add("Sanath Jayasuriya");
        cricketPlayers.add("Mushfiqur Rahim");
        cricketPlayers.add("Shakib Al Hasan");
        cricketPlayers.add("Mominul Haque");
        cricketPlayers.add("Dane van Niekerk");
        cricketPlayers.add("Sophie Ecclestone");
        cricketPlayers.add("Megan Schutt");
        cricketPlayers.add("Sophie Ecclestone");
        cricketPlayers.add("Lauren Winfield");
        cricketPlayers.add("Heather Knight");
        cricketPlayers.add("Alyssa Healy");
        cricketPlayers.add("Megan Schutt");

        Intent type = getIntent();
        id = type.getIntExtra("GameType",0);
        Random r = new Random();
        if (id == 1){
            currentIndex = r.nextInt(movies.size());
            currentWord = movies.get(currentIndex);
            backGround.setImageResource(R.drawable.kmb);
        }
        else if (id == 2){
            currentIndex = r.nextInt(hollyMovies.size());
            currentWord = hollyMovies.get(currentIndex);
            backGround.setImageResource(R.drawable.hb1);
        }
        else if (id == 3){
            currentIndex = r.nextInt(kollyMovies.size());
            currentWord = kollyMovies.get(currentIndex);
            backGround.setImageResource(R.drawable.kms);
        }
        else if(id == 4){
            currentIndex = r.nextInt(songs.size());
            currentWord = songs.get(currentIndex);
            backGround.setImageResource(R.drawable.sb);
        }
        else if (id == 5) {
            currentIndex = r.nextInt(hollySongs.size());
            currentWord = hollySongs.get(currentIndex);
            backGround.setImageResource(R.drawable.hs);
        }
        else if (id == 6) {
            currentIndex = r.nextInt(kollySongs.size());
            currentWord = kollySongs.get(currentIndex);
            backGround.setImageResource(R.drawable.ks);
        }
        else if (id == 7) {
            currentIndex = r.nextInt(stars.size());
            currentWord = stars.get(currentIndex);
            backGround.setImageResource(R.drawable.so);
        }
        else if (id == 8) {
            currentIndex = r.nextInt(hollyStars.size());
            currentWord = hollyStars.get(currentIndex);
            backGround.setImageResource(R.drawable.hss);
        }
        else if (id == 9) {
            currentIndex = r.nextInt(kollyStars.size());
            currentWord = kollyStars.get(currentIndex);
            backGround.setImageResource(R.drawable.kss);
        }
        else {
            currentIndex = r.nextInt(cricketPlayers.size());
            currentWord = cricketPlayers.get(currentIndex);
            backGround.setImageResource(R.drawable.cp1);
        }

        blanks = new StringBuffer();
        for (int i = 0; i < currentWord.length(); i++) {
            if (currentWord.charAt(i) == ' ') {
                blanks.append("  ");
            } else {
                blanks.append("_ ");
            }
        }
        space.setText(blanks.toString().trim());
    }

    public void check(View v) {
        Button clickedButton = (Button) v;
        enteredCharacter = clickedButton.getText().toString();
        boolean correctGuess = false;

        for (int j = 0; j < currentWord.length(); j++) {
            String currentChar = String.valueOf(currentWord.charAt(j));
            if (enteredCharacter.equalsIgnoreCase(currentChar)) {
                if (currentWord.charAt(j) == ' ') {
                    continue;
                }
                else {
                    blanks.replace(2 * j, 2 * j + 1, currentChar);
                    correctGuess = true;
                }
            }
        }

        if (!correctGuess) {
            totalAttempts++;
            updateHangmanImage(totalAttempts);
        }
        v.setVisibility(View.INVISIBLE);
        space.setText(blanks.toString().trim());
        checkGameStatus();
    }

    private void updateHangmanImage(int totalAttempts) {
        if (totalAttempts == 1) {
            hangman.setImageResource(R.drawable.hhead);
        } else if (totalAttempts == 2) {
            hangman.setImageResource(R.drawable.hbody);
        } else if (totalAttempts == 3) {
            hangman.setImageResource(R.drawable.htleg);
        } else if (totalAttempts == 4) {
            hangman.setImageResource(R.drawable.hthands);
        } else {
            hangman.setImageResource(R.drawable.hdead);
            checkGameStatus();
        }
    }

    private void checkGameStatus() {
        if (blanks.indexOf("_") == -1) {
            gameOver.setImageResource(R.drawable.yw);
            anim = AnimationUtils.loadAnimation(this, R.anim.scale_hangman);
            gameOver.setAnimation(anim);
            gameOver.setVisibility(View.VISIBLE);
        } else if (totalAttempts == 5) {
            gameOver.setImageResource(R.drawable.go);
            anim = AnimationUtils.loadAnimation(this, R.anim.scale_hangman);
            gameOver.setAnimation(anim);
            gameOver.setVisibility(View.VISIBLE);
            space.setText(currentWord);
        }
    }

    public void homePage() {
        Intent i = new Intent(this, MainActivity.class);
        startActivity(i);
    }
}

